resources:
- auth-deployment.yaml
- web-deployment.yaml
- ingestion-deployment.yaml
- summarizer-deployment.yaml
- discord-deployment.yaml
- tunnel-deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: sift-auth
  newName: sift-auth
  newTag: "1789629980"
- name: sift-discord
  newName: sift-discord
  newTag: "1789626826"
- name: sift-ingestion
  newName: sift-ingestion
  newTag: "1789459392"
- name: sift-summarizer
  newName: sift-summarizer
  newTag: "1789682802"
- name: sift-web
  newName: sift-web
  newTag: "1789546173"
