/* GENERATED by scripts/sync-branding.js from branding/branding.yaml - do not edit */
export const brand = {
  name: "Sift" as const,
  tagline: "Your inbox, sifted." as const,
  urlFallback: "https://sift.falaktulsi.com" as const,
  email: {
    pageBg: "#f4f2ec" as const,
    cardBg: "#ffffff" as const,
    cardBorder: "#e6e1d6" as const,
    headerBg: "#1c2430" as const,
    mark: "#f7f3ea" as const,
    title: "#1c2430" as const,
    body: "#4a5563" as const,
    muted: "#7a8494" as const,
    footer: "#8a93a3" as const,
    ctaBg: "#c4a35a" as const,
    ctaText: "#1c2430" as const,
    linkFallback: "#5b6575" as const,
  },
} as const;

